# Generated by Django 5.1.6 on 2025-03-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_term', models.CharField(max_length=100, unique=True)),
                ('eng_desc', models.TextField()),
                ('transcription', models.CharField(max_length=50)),
                ('rus_term', models.CharField(max_length=100)),
                ('rus_desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to=settings.AUTH_USER_MODEL)),
                ('entries', models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.dictionaryentry')),
                ('tags', models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dictionary.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_phrase', models.CharField(max_length=200)),
                ('rus_phrase', models.CharField(max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionary.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, help_text='Формат: АААА-ЦЦ-ЦЦЦ() (например, АААА-12-345())', max_length=10, null=True, verbose_name='Группа')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_card_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card_set')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
