# Generated by Django 5.1.6 on 2025-03-23 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Можно использовать HTML для форматирования текста', verbose_name='Содержание')),
                ('file', models.FileField(blank=True, help_text='Загрузите файл (например, изображение или документ)', null=True, upload_to='articles/files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_term', models.CharField(max_length=100, unique=True, verbose_name='Английский термин')),
                ('eng_desc', models.TextField(verbose_name='Описание на английском')),
                ('transcription', models.CharField(max_length=50, verbose_name='Транскрипция')),
                ('rus_term', models.CharField(max_length=100, verbose_name='Русский термин')),
                ('rus_desc', models.TextField(verbose_name='Описание на русском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудио')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись словаря',
                'verbose_name_plural': 'Записи словаря',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('entries', models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.dictionaryentry', verbose_name='Записи')),
                ('tags', models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Набор карточек',
                'verbose_name_plural': 'Наборы карточек',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст примера')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.dictionaryentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dictionary.dictionaryentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_phrase', models.CharField(max_length=200, verbose_name='Фраза на английском')),
                ('rus_phrase', models.CharField(max_length=200, verbose_name='Фраза на русском')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionary.dictionaryentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
        migrations.CreateModel(
            name='DictionaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry', verbose_name='Запись')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег словаря',
                'verbose_name_plural': 'Теги словаря',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, help_text='Формат: АБВГ-ЦЦ-ЦЦ (например, АБВГ-12-34)', max_length=10, null=True, verbose_name='Группа')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='ВКонтакте')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='VocabularyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('is_default', models.BooleanField(default=False, verbose_name='Тема по умолчанию (Все слова)')),
                ('entries', models.ManyToManyField(blank=True, related_name='vocabulary_topics', to='dictionary.dictionaryentry', verbose_name='Записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_topics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тема словарника',
                'verbose_name_plural': 'Темы словарника',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cardset', verbose_name='Набор карточек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_card_sets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный набор карточек',
                'verbose_name_plural': 'Избранные наборы карточек',
                'unique_together': {('user', 'card_set')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry', verbose_name='Запись')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная запись',
                'verbose_name_plural': 'Избранные записи',
                'unique_together': {('user', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteVocabularyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vocabulary_topics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.vocabularytopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Избранная тема словарника',
                'verbose_name_plural': 'Избранные темы словарника',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
