# Generated by Django 5.1.6 on 2025-03-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='cardset',
            options={'verbose_name': 'Card Set', 'verbose_name_plural': 'Card Sets'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'verbose_name': 'Dictionary Entry', 'verbose_name_plural': 'Dictionary Entries'},
        ),
        migrations.AlterModelOptions(
            name='dictionarytag',
            options={'verbose_name': 'Dictionary Tag', 'verbose_name_plural': 'Dictionary Tags'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Example', 'verbose_name_plural': 'Examples'},
        ),
        migrations.AlterModelOptions(
            name='favoritecardset',
            options={'verbose_name': 'Favorite Card Set', 'verbose_name_plural': 'Favorite Card Sets'},
        ),
        migrations.AlterModelOptions(
            name='favoriteentry',
            options={'verbose_name': 'Favorite Entry', 'verbose_name_plural': 'Favorite Entries'},
        ),
        migrations.AlterModelOptions(
            name='favoritevocabularytopic',
            options={'verbose_name': 'Favorite Vocabulary Topic', 'verbose_name_plural': 'Favorite Vocabulary Topics'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'verbose_name': 'Phrase', 'verbose_name_plural': 'Phrases'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='vocabularytopic',
            options={'verbose_name': 'Vocabulary Topic', 'verbose_name_plural': 'Vocabulary Topics'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='You can use HTML to format the text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file (e.g., image or document)', null=True, upload_to='articles/files/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='card_sets', to='dictionary.tag'),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='eng_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='eng_term',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='rus_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='rus_term',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='transcription',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionarytag',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='dictionarytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.tag'),
        ),
        migrations.AlterField(
            model_name='example',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='favoritecardset',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.cardset'),
        ),
        migrations.AlterField(
            model_name='favoritecardset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_card_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='favoriteentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritevocabularytopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.vocabularytopic'),
        ),
        migrations.AlterField(
            model_name='favoritevocabularytopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vocabulary_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='eng_phrase',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='rus_phrase',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, help_text='Format: АБВГ-ЦЦ-ЦЦ (e.g., АБВГ-12-34)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='vocabulary_topics', to='dictionary.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabularytopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
