# Generated by Django 5.1.6 on 2025-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_article_options_alter_cardset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='cardset',
            options={'verbose_name': 'Набор карточек', 'verbose_name_plural': 'Наборы карточек'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'verbose_name': 'Словарная запись', 'verbose_name_plural': 'Словарные записи'},
        ),
        migrations.AlterModelOptions(
            name='dictionarytag',
            options={'verbose_name': 'Тег словарной записи', 'verbose_name_plural': 'Теги словарных записей'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
        migrations.AlterModelOptions(
            name='favoritecardset',
            options={'verbose_name': 'Избранный набор карточек', 'verbose_name_plural': 'Избранные наборы карточек'},
        ),
        migrations.AlterModelOptions(
            name='favoriteentry',
            options={'verbose_name': 'Избранная запись', 'verbose_name_plural': 'Избранные записи'},
        ),
        migrations.AlterModelOptions(
            name='favoritevocabularytopic',
            options={'verbose_name': 'Избранная тема словарника', 'verbose_name_plural': 'Избранные темы словарника'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'verbose_name': 'Фраза', 'verbose_name_plural': 'Фразы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='vocabularytopic',
            options={'verbose_name': 'Тема словарника', 'verbose_name_plural': 'Темы словарника'},
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='eng_desc',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='rus_desc',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Вы можете использовать HTML для форматирования текста'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, help_text='Загрузите файл (например, изображение или документ)', null=True, upload_to='articles/files/'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='transcription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, help_text='Формат: АБВГ-ЦЦ-ЦЦ (например, АБВГ-12-34)', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dictionarytag',
            unique_together={('entry', 'tag')},
        ),
    ]
